### ISSUE TITLE
Fails to build for s390x

### ISSUE THREAD

**Issue by andypost** [nhorman/rng-tools#46]
Upgrade to 6.6 on Alpinelinux fails on s390x https://github.com/alpinelinux/aports/pull/6282

Build log https://build.alpinelinux.org/buildlogs/build-edge-ppc64le/community/rng-tools/rng-tools-6.6-r0.log

```
rngd_darn.c: In function 'refill_rand':
rngd_darn.c:129:15: error: 'struct rng' has no member named 'options'; did you mean 'rng_options'?
  if (ent_src->options[DARN_USE_AES].int_val) {
               ^~~~~~~
               rng_options
rngd_darn.c:129:23: error: 'DARN_USE_AES' undeclared (first use in this function); did you mean 'DARN_OPT_AES'?
  if (ent_src->options[DARN_USE_AES].int_val) {
                       ^~~~~~~~~~~~
                       DARN_OPT_AES
rngd_darn.c:129:23: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by andypost** [comment]
Guess this change introduced in https://github.com/nhorman/rng-tools/releases/tag/v6.4

**Comment by nhorman** [comment]
It was introduced in commit e6c7f66f83e1653d0b8d1045f59bd00fb9a6dd71, and subsequently fixed in commit 901468598270db9c9f19f63f9812a94f5a44a487

**Comment by andypost** [comment]
Thanx a lot! now it fixed with the patch and upgrade to 6.7 pending because there's new dependency on libp11

**Comment by nhorman** [comment]
You can disable the p11 dependency by configuring --without-pkcs11

Neil
