### ISSUE TITLE
rng-tools stopped to build with jitterentropy v3.4.0

### ISSUE THREAD

**Issue by nefigtut** [nhorman/rng-tools#164]
Now a build errors out with:

```
rngd_jitter.c: In function 'rngd_notime_start':
rngd_jitter.c:56:45: error: invalid use of undefined type 'struct jent_notime_ctx'
   56 |         ret = -pthread_attr_init(&thread_ctx->notime_pthread_attr);
```

It looks like this is result of a commit https://github.com/smuellerDD/jitterentropy-library/commit/8373b05f1a55878f348d365f05b046ff42d2f9ce which now hides `struct jent_notime_ctx` under `#ifdef JENT_CONF_ENABLE_INTERNAL_TIMER` in `jitterentropy.h`.

jitterentropy's `Makefile` sets `JENT_CONF_ENABLE_INTERNAL_TIMER` unconditionally:

```
# Enable internal timer support
CFLAGS += -DJENT_CONF_ENABLE_INTERNAL_TIMER
```

but rng-tools which use `jitterentropy.h` do not touch `JENT_CONF_ENABLE_INTERNAL_TIMER` at all, so `struct jent_notime_ctx` becomes hidden.

It looks to me **(a personal opinion which can be wrong)** that this is a design error in the jitterentropy library itself. Users of a library may not know how the library was built. I.e. I believe, `#ifdef JENT_CONF_ENABLE_INTERNAL_TIMER` should not be used in `jitterentropy.h`.

Unfortunately, I was not able to invent a good solution. I've come up with a dirty hack (which is wrong and should not be like this, but it works) of defining `#ifdef JENT_CONF_ENABLE_INTERNAL_TIMER` in rng-tools' `configure.ac`. The diff is:

```
--- configure.ac	2022-03-24 13:14:11.000000000 +0100
+++ configure.ac.new	2022-03-24 15:58:56.187367770 +0100
@@ -95,7 +95,10 @@ AS_IF(
 				[AM_CONDITIONAL([JITTER], [true])
 				AC_DEFINE([HAVE_JITTER],1,[Enable JITTER])
 				AC_CHECK_LIB(jitterentropy, jent_notime_settick,
-				[AC_DEFINE([HAVE_JITTER_NOTIME],1,[Enable JITTER_NOTIME])],
+				[
+					AC_DEFINE([HAVE_JITTER_NOTIME],1,[Enable JITTER_NOTIME])
+					AC_DEFINE([JENT_CONF_ENABLE_INTERNAL_TIMER],1,[Enable JENT_CONF_ENABLE_INTERNAL_TIMER])
+				],
 				[],-lpthread)],
 				AC_MSG_NOTICE([No Jitterentropy library found]),-lpthread)
 	], [AC_MSG_NOTICE([Disabling JITTER entropy 
```

I'm sure this is not a good solution, that's why I'm creating an issue and not a pull request. Could we please discuss how this can be fixed properly?

**Comment by nhorman** [comment]
Hey Vladis!  I had this same report earlier last week,  I think you will find its been fixed by commit e2698477e8abf623c18ab28d33cc894ec882a706 .  Please confirm for me if you would.

At some point in time @smuellerDD changed some things around in jitter (or perhaps I never tried building without the internal timer).  Either way, that change looks for a function that should only be defined if the internal timer define is set in the compiled jitter library

**Comment by smuellerDD** [comment]
Am Freitag, 25. März 2022, 13:49:54 CET schrieb Neil Horman:

Hi Neil,

> Hey Vladis!  I had this same report earlier last week,  I think you will
> find its been fixed by commit e2698477e8abf623c18ab28d33cc894ec882a706 . 
> Please confirm for me if you would.
> 
> At some point in time @smuellerDD changed some things around in jitter (or
> perhaps I never tried building without the internal timer).  Either way,
> that change looks for a function that should only be defined if the
> internal timer define is set in the compiled jitter library

Do you have a suggestion how the library should report that the notime support 
is compiled?

Ciao
Stephan

**Comment by nhorman** [comment]
@smuellerDD I think we're ok for now, stephan.  Checking the settick function at rng-tools compile time seems to be working ok.  The goal (or rather my goal), is to be able to determine at rng-tools build time if the jitterentropy library was configured to support internal timers.  So far checking for settick does that.  A longer term solution might be to have jitterentropy produce a header file that defines internal timer support so I can just check that at build time without having to add a configuration check, but that can be an in-the-future thing

**Comment by smuellerDD** [comment]
Am Freitag, 25. März 2022, 14:16:31 CET schrieb Neil Horman:

Hi Neil,

> @smuellerDD I think we're ok for now, stephan.  Checking the settick
> function at rng-tools compile time seems to be working ok.  The goal (or
> rather my goal), is to be able to determine at rng-tools build time if the
> jitterentropy library was configured to support internal timers.  So far
> checking for settick does that.  A longer term solution might be to have
> jitterentropy produce a header file that defines internal timer support so
> I can just check that at build time without having to add a configuration
> check, but that can be an in-the-future thing

Thanks for the suggestion. Let me mull it over.

Ciao
Stephan

**Comment by nefigtut** [comment]
Hi, Neil, Stephan,
Thank you for your attention and replies!

> I think you will find its been fixed by commit [e269847](https://github.com/nhorman/rng-tools/commit/e2698477e8abf623c18ab28d33cc894ec882a706) . Please confirm for me if you would.

Unfortunately, it is not. Yes, a configure process detects `jent_notime_settick()` presence and sets `HAVE_JITTER_NOTIME`, that's all fine. But `struct jent_notime_ctx` is still hidden under `#ifdef JENT_CONF_ENABLE_INTERNAL_TIMER` and it is not defined. So `rngd` code still does not see `struct jent_notime_ctx` even with defined `HAVE_JITTER_NOTIME`.

My solution is to just define `JENT_CONF_ENABLE_INTERNAL_TIMER` and the same place as `HAVE_JITTER_NOTIME`, but I believe this is not a good solution, since we have two defines (`JENT_CONF_ENABLE_INTERNAL_TIMER` on the jitterlib side and `HAVE_JITTER_NOTIME` on the rngd side) for exactly same thing. Unfortunately, I do not see how to do this right.

**Comment by nhorman** [comment]
ah, crap.  That solution won't work either, Vladis, as it implies that libjitterentropy will be built at the same time that rngd is, and thats not guaranateed.

@smuellerDD what we really need is a mechanism that tells us if libjitterentropy.so and libjitterentropy.a were built with JENT_CONF_ENABLE_INTERNAL_TIMER defined.  Usually i use autoconf or cmake  to create defines that can be exported for use by consuming programs, which would solve the issue here, but you're not using a makefile generator here, so I'm not sure how you might best create that

**Comment by nefigtut** [comment]
> That solution won't work either, Vladis, as it implies that libjitterentropy will be built at the same time that rngd is, and thats not guaranateed.

Hi, Neil! Let me argue with you )) My "solution" of defining `JENT_CONF_ENABLE_INTERNAL_TIMER` in `configure.ac` works, at least, `rng-tools` builds fine in Fedora's Koji with jitterentropy-3.4.0, which was built days before. Surely, that can be a false positive, I'm afraid, I do not get all that in 100%.

> what we really need is a mechanism that tells us if libjitterentropy.so and libjitterentropy.a were built with JENT_CONF_ENABLE_INTERNAL_TIMER defined.

My (amateur) thought on this would be the following. `jitterentropy.h` should not contain defines set during the build time. This can be done as Neil suggests - by generating a proper `jitterentropy.h` during a build time. Or just by removing `#ifdef JENT_CONF_ENABLE_INTERNAL_TIMER` and friends (if any). Yes, that would expose `struct jent_notime_ctx` and notime functions, but I do not see why this is bad if they are just stubs.

**Comment by nhorman** [comment]
Sorry, let me be more specific in my statement.

Your solution will work, but only if it is an accurate reflection of how libjitterentropy was actually built.  By defining JENT_CONF_ENABLE_INTERNAL_TIMER in rng-tools, you create the symbols/macros that you need for it to build properly, but if jitterentropy wasn't actually built with that flag set as well, you can find yourself in a situation in which rngd thinks jitter offers an internal timer, when it really doesn't.

What we need is a way for jitterentropy to communicate to any consuming application, how jitterentropy was built (with or without an internal timer), so that the consuming application can be built accordingly.  What would be even better would be a way to tell at runtime if the feature is enabled.

**Comment by nefigtut** [comment]
Thanks, Neil, this makes perfect sense.

**Comment by nefigtut** [comment]
@nhorman i've ended up with a fix for configure.ac i've mentioned in my first message. jent_notime_settick() is hidden behind #ifdef JENT_CONF_ENABLE_INTERNAL_TIMER. the other #ifdef branch has static inline int jent_notime_settick(), so it is not visible externally. until that stays (yes, this is not granted for a future), jent_notime_settick() visibility definitely means JENT_CONF_ENABLE_INTERNAL_TIMER is set, i believe. i don't like this hack quite much but it works as of now.

**Comment by nefigtut** [comment]
thanks, Neil @nhorman !

**Comment by nefigtut** [comment]
i'm afraid rng-tools builds after `c29424f10a0d ("Adjust jitterentropy library to timeout/fail on long delay")` has a bug. i'm not creating a new issue, since the bug is directly related to this issue. the commit message says:

```
When jitterentropy is built without internal
timers, jent_notime_init is defined publically, but when it is built
with timers, its declared as a static symbol, preenting resolution, so
we can test to see if the function exists.
```
i believe this is not correct, since the following code:

``` [ jitterentropy.h ]
#define JENT_PRIVATE_STATIC __attribute__((visibility("default")))    // this line is used in public Linux builds

#ifdef JENT_CONF_ENABLE_INTERNAL_TIMER  // is always defined

JENT_PRIVATE_STATIC
int jent_notime_init(void **ctx);

#else

static inline int jent_notime_init(void **ctx) { (void)ctx; return 0; } // (1)

#endif /* JENT_CONF_ENABLE_INTERNAL_TIMER */
```

suggests the opposite. please, look at line (1), jent_notime_init() here is no-op, i.e. no internal timers, and it is static (i.e. invisible). this is opposite to what commit message says.

I believe, we need to swap true and false branches of `AC_CHECK_LIB(jitterentropy, jent_notime_init, ` and add `JENT_CONF_ENABLE_INTERNAL_TIMER` fix i've suggested earlier.

I'm going to do this for Fedora. Neil, would you be interested in this patch posted here?

**Comment by nhorman** [comment]
yeah, if it works for you, please post a PR here, I'll merge it.

**Comment by nhorman** [comment]
closing based on fix from https://github.com/nhorman/rng-tools/pull/180
